from abc import ABC, abstractmethod
from typing import List, Dict
from .models import WatchItem, TitleMetadata
class Repository(ABC):
    @abstractmethod
    def save(self, item: WatchItem, meta: TitleMetadata) -> int: ...
    @abstractmethod
    def find(self, q: str) -> List[WatchItem]: ...
    @abstractmethod
    def update_status(self, item_id: int, status: str) -> None: ...
    @abstractmethod
    def remove(self, item_id: int) -> None: ...
    @abstractmethod
    def summary(self) -> Dict[str, float]: ...
class MetadataProvider(ABC):
    @abstractmethod
    def fetch(self, title: str) -> TitleMetadata: ...
